# Extend base image with plugins.
FROM etfxdev/peatio:latest

# Copy Gemfile.plugin for installing plugins.
COPY Gemfile.plugin $APP_HOME

# Install plugins.
RUN bundle install --path /opt/vendor/bundle
